version: "3.8"

services:
  app:
    build: .
    image: craiyon-website:latest
    container_name: craiyon-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Provide one or more Nebius API keys (comma-separated)
      # Example: NEBIUS_API_KEYS=key1,key2,key3
      - NEBIUS_API_KEYS=${NEBIUS_API_KEYS}
      # Or set a single key
      - NEBIUS_API_KEY=${NEBIUS_API_KEY}
    volumes:
      - craiyon_data:/app/data
    restart: unless-stopped
    depends_on:
      - init-db

  # One-shot service to initialize/seed the SQLite DB into the shared volume
  init-db:
    build: .
    image: craiyon-website:latest
    container_name: craiyon-init
    command: npm run init-db
    environment:
      - NODE_ENV=production
    volumes:
      - craiyon_data:/app/data
    restart: "no"

volumes:
  craiyon_data:
    driver: local
